"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = __importDefault(require("./auth"));
const employee_1 = __importDefault(require("./employee"));
const attendance_1 = __importDefault(require("./attendance"));
const leave_1 = __importDefault(require("./leave"));
const task_1 = __importDefault(require("./task"));
const payroll_1 = __importDefault(require("./payroll"));
const department_1 = __importDefault(require("./department"));
const calendar_1 = __importDefault(require("./calendar"));
const reports_1 = __importDefault(require("./reports"));
const dailyReport_1 = __importDefault(require("./dailyReport"));
const message_1 = __importDefault(require("./message"));
const notification_1 = __importDefault(require("./notification"));
const upload_1 = __importDefault(require("./upload"));
const timesheet_1 = __importDefault(require("./timesheet"));
const router = (0, express_1.Router)();
router.use('/auth', auth_1.default);
router.use('/employees', employee_1.default);
router.use('/attendance', attendance_1.default);
router.use('/leaves', leave_1.default);
router.use('/tasks', task_1.default);
router.use('/payroll', payroll_1.default);
router.use('/departments', department_1.default);
router.use('/calendar', calendar_1.default);
router.use('/reports', reports_1.default);
router.use('/daily-reports', dailyReport_1.default);
router.use('/messages', message_1.default);
router.use('/notifications', notification_1.default);
router.use('/uploads', upload_1.default);
router.use('/timesheets', timesheet_1.default);
exports.default = router;
